version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  nodeapp:
    build: .
    container_name: nodeapp
    ports:
      - "3000:3000"
    working_dir: /app
    command: ["node", "index.js"]
    volumes:
      - .:/app

volumes:
  jenkins_home: 